### ISSUE TITLE
Start checking options for CD

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/LeanMood#134]
We need to start sneaking into adding CD to our front end build process.

The idea is:

- Fire a build when master changes to a dev server.
- Hosting option could be Heroku.
- We have to check for pricing, rather than using the free instace (limited number of hours / cpu) check pricing to have it a small instance but working 24 hours per day.

Prepare a brief summary and present it on a friday team session :).

Cheers
  Braulio

**Comment by Nasdan** [comment]
I had create an issue to configure CD #137
