### ISSUE TITLE
Refactor entities id field to string

### ISSUE THREAD

**Issue by Nasdan** [Lemoncode/LeanMood#165]
Change `id` types to string instead of int.

**Comment by fjcalzado** [comment]
@Nasdan I did re-typed Id field as a `string` for the following entities:
- `Training`
- `TrainingSummary`

1) Do you want me to also refactor Id for `Trainer`and `Student`?
2) Eventhough now Ids are strings, Edit Training page doesn't work. 404 again.

**Comment by Nasdan** [comment]
1. Yes, we need to change `Id` for all entities.
2. Maybe, it's because we need the previous refactor?
