### ISSUE TITLE
Layout login page

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/LeanMood#6]
Build the layout login page (keep in the footer the links to the other pages as something temporary).

This layout is defined under: ./src/components/pages/login/index.tsx

Since we are working on tsx and no HTML, some things will need some updates, just buzz me and we can go through this.

Task assigned to: @barandag  waiting for him to accept the invite and join the team

**Comment by vicmator** [comment]
I have been seeing the structure and Login page is under ./src/pages/general/login/page.tsx

I think that I have to create the login page under ./src/pages/general/login/page.tsx and I have to create the component folder with the header and form page.

In header component I would put the content that now have the page.tsx:

`export class LoginPage extends React.Component<Props, {}> {
   public render() {
       return (
          <div>
            <span> Login: </span>
             <br/>
             <span> Navigation Skeleton:</span><Link to="/admin">Go to admin MODULE</Link>
             <br/>
             <span> Navigation Skeleton:</span><Link to="/students">Go to students MODULE</Link>
             <span>*****</span>
             <br/>
             <Link to="/nonexistingpage">Navigate to a 404 page.</Link>
             <br/>
             <br/>
             <span> PENDING Trainers module navigation, any volunteer?</span>
             <br/>

          </div>
       );
  }
}`

and then in page.tsx I put the header and the form component centered.

What do you think?

**Comment by brauliodiez** [comment]
I would say, you have the page (login/page)

Then inside the components subfolder, there you can create the loginForm components

In the loginPage let's do the follwoing (pseudocode)

```html
<div>
 <LoginFormComponent/>
  <div class="row>
<span> Navigation Skeleton:</span><Link to="/admin">Go to admin MODULE</Link>
             <br/>
             <span> Navigation Skeleton:</span><Link to="/students">Go to students MODULE</Link>
             <span>*****</span>
             <br/>
             <Link to="/nonexistingpage">Navigate to a 404 page.</Link>
             <br/>
             <br/>
             <span> PENDING Trainers module navigation, any volunteer?</span>
             <br/>
  </div>
</div>
```

**Comment by brauliodiez** [comment]
Checklist to add:

- Add validation (lc-formvalidation).
- Promote to common "input"
